spring:
  profiles.active: dev
  mvc.favicon.enabled: false
  autoconfigure.exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

logging:
    level:
        it.euris.fullstack: INFO
        org.springframework: INFO

---
spring:
  profiles: dev
  autoconfigure.exclude: 
mongo.db.name: test

---
spring:
  profiles: prod
